services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8001:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
    restart: unless-stopped
    networks:
      - rag-network

  rag-app:
    build: .
    container_name: rag-app
    ports:
      - "8000:8000"
    volumes:
      - ./data/airbnblisting.txt:/app/data/airbnblisting.txt
    environment:
      - CHROMA_SERVER_HOST=chromadb
      - CHROMA_SERVER_PORT=8000
      - CHROMA_SERVER_HTTP_PORT=8000
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    depends_on:
      - chromadb
    restart: unless-stopped
    networks:
      - rag-network

volumes:
  chromadb_data:
    driver: local

networks:
  rag-network:
    driver: bridge